<Project Sdk="Remora.Resonite.Sdk">
  <PropertyGroup>
    <PackageId>MonkeyLoader.ModTemplate.Resonite</PackageId>
    <Title>MonkeyLoader Resonite Mod Template</Title>
    <Authors>Banane9</Authors>
    <Version>0.5.0</Version>
    <Description>This is a template for a Resonite MonkeyLoader mod.</Description>
    <PackageLicenseExpression>LGPL-3.0-or-later</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/ResoniteModdingGroup/MonkeyLoader.ModTemplate</PackageProjectUrl>
    <RepositoryUrl>$(PackageProjectUrl).git</RepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>mod; mods; monkeyloader; resonite</PackageTags>
    <TargetsForTfmSpecificContentInPackage>$(TargetsForTfmSpecificContentInPackage);AddExtraFilesToPackage</TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <PropertyGroup>
    <EnablePackageValidation>true</EnablePackageValidation>

    <!-- Optional: Detect breaking changes from a previous stable version
    <PackageValidationBaselineVersion>0.1.0-beta</PackageValidationBaselineVersion> -->
  </PropertyGroup>

  <Target Name="AddExtraFilesToPackage">
    <ItemGroup>
      <TfmSpecificPackageFile Include="$(ProjectDir)../MonkeyLoader.ModTemplate.PrePatcher/bin/$(Configuration)/mod/client/MonkeyLoader.ModTemplate.PrePatcher.*" PackagePath="lib/$(TargetFramework)/pre-patchers/" />
    </ItemGroup>
  </Target>
  
  <ItemGroup>
    <None Include="../README.md" Pack="true" PackagePath="" />
    <None Include="Locale/*" Pack="true" PackagePath="content/Locale/" />
  </ItemGroup>

  <ItemGroup>
    <ResoniteReference Include="FrooxEngine" />
    <ResoniteReference Include="Elements.Core" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../MonkeyLoader.ModTemplate.PrePatcher/MonkeyLoader.ModTemplate.PrePatcher.csproj" PrivateAssets="All" />
  </ItemGroup>
</Project>
